/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDZTuwaUXiDYJ6WRKsQkGks3CjSB62rU',
    appId: '1:772198720708:web:c75f44edbe1fc85e54d591',
    messagingSenderId: '772198720708',
    projectId: 'edav1-adcd0',
    authDomain: 'edav1-adcd0.firebaseapp.com',
    storageBucket: 'edav1-adcd0.firebasestorage.app',
    measurementId: 'G-VP2SVRHR87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcuyZ-aq2zY9h-NDmgEIssXFJoHlre56o',
    appId: '1:772198720708:android:1be8c7825c4d83e754d591',
    messagingSenderId: '772198720708',
    projectId: 'edav1-adcd0',
    storageBucket: 'edav1-adcd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACFA9WHQ9snIX_xF_G1bQcipqePdb_DxU',
    appId: '1:772198720708:ios:f5bf8479400ff69e54d591',
    messagingSenderId: '772198720708',
    projectId: 'edav1-adcd0',
    storageBucket: 'edav1-adcd0.firebasestorage.app',
    iosBundleId: 'com.example.eda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACFA9WHQ9snIX_xF_G1bQcipqePdb_DxU',
    appId: '1:772198720708:ios:f5bf8479400ff69e54d591',
    messagingSenderId: '772198720708',
    projectId: 'edav1-adcd0',
    storageBucket: 'edav1-adcd0.firebasestorage.app',
    iosBundleId: 'com.example.eda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCDZTuwaUXiDYJ6WRKsQkGks3CjSB62rU',
    appId: '1:772198720708:web:44032392cd12f78854d591',
    messagingSenderId: '772198720708',
    projectId: 'edav1-adcd0',
    authDomain: 'edav1-adcd0.firebaseapp.com',
    storageBucket: 'edav1-adcd0.firebasestorage.app',
    measurementId: 'G-0F09WZYKZM',
  );
}
*/
